/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author MustainE
 */
public class RCompraContrato extends javax.swing.JInternalFrame {

    public RCompraContrato() {
        initComponents();
        btnRegistrar.setEnabled(false);
        //btnNuevo.setEnabled(true);
        txtId.setEnabled(false);
        txtRSocial.setEnabled(false);
        txtDireccion.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtEmpresa = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        txtRSocial2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtAperturaContrato = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        txtId1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnEditar2 = new javax.swing.JButton();
        btnNuevo1 = new javax.swing.JButton();
        jcbEstado = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        txtRSocial1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtId2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtId3 = new javax.swing.JTextField();
        txtRSocial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtId4 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtId5 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtId6 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 0, 51));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("..Registro Tipo Documento..");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 51), 1, true), "Mantenimiento de Apertura Contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(153, 0, 51))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(153, 0, 51));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtId.setForeground(new java.awt.Color(0, 0, 102));
        txtId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtId.setEnabled(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 110, 20));

        jtEmpresa.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtEmpresa.setForeground(new java.awt.Color(51, 51, 255));
        jtEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtEmpresa.setGridColor(new java.awt.Color(0, 51, 153));
        jScrollPane1.setViewportView(jtEmpresa);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 400, 230));

        jSeparator1.setForeground(new java.awt.Color(153, 0, 51));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 750, 10));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 0, 51));
        jLabel22.setText("Falta Comprar:");
        jLabel22.setToolTipText("");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, -1, 20));

        txtRSocial2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtRSocial2.setForeground(new java.awt.Color(0, 0, 102));
        txtRSocial2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtRSocial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 360, 20));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 51));
        jLabel6.setText("Buscar Apertura Contrato:");
        jLabel6.setToolTipText("");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        jtAperturaContrato.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtAperturaContrato.setForeground(new java.awt.Color(51, 51, 255));
        jtAperturaContrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtAperturaContrato.setGridColor(new java.awt.Color(0, 51, 153));
        jScrollPane2.setViewportView(jtAperturaContrato);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 760, 220));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 0, 51));
        jLabel26.setText("Total Compra:");
        jLabel26.setToolTipText("");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, 20));

        txtId1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtId1.setForeground(new java.awt.Color(0, 0, 102));
        txtId1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtId1.setEnabled(false);
        txtId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 110, 20));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 51), 1, true), "Registro Compra Contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 11), new java.awt.Color(153, 0, 51))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setBackground(new java.awt.Color(153, 0, 51));
        btnRegistrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 153));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 100, 30));

        btnEditar2.setBackground(new java.awt.Color(153, 0, 51));
        btnEditar2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEditar2.setForeground(new java.awt.Color(0, 0, 153));
        btnEditar2.setText("Editar");
        btnEditar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnEditar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 100, 30));

        btnNuevo1.setBackground(new java.awt.Color(153, 0, 51));
        btnNuevo1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNuevo1.setForeground(new java.awt.Color(0, 0, 153));
        btnNuevo1.setText("Nuevo");
        btnNuevo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnNuevo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 100, 30));

        jcbEstado.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jcbEstado.setForeground(new java.awt.Color(0, 0, 153));
        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jcbEstado.setToolTipText("");
        jcbEstado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel3.add(jcbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 150, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 0, 51));
        jLabel19.setText("Estado:");
        jLabel19.setToolTipText("");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        txtRSocial1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtRSocial1.setForeground(new java.awt.Color(0, 0, 102));
        txtRSocial1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(txtRSocial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 130, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 51));
        jLabel5.setText("Importe Total:");
        jLabel5.setToolTipText("");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        txtDireccion.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(0, 0, 102));
        txtDireccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 90, -1));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 0, 51));
        jLabel25.setText("Precio:");
        jLabel25.setToolTipText("");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));
        jPanel3.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 110, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 0, 51));
        jLabel21.setText("Fecha:");
        jLabel21.setToolTipText("");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("idCContrato:");
        jLabel1.setToolTipText("");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        txtId2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtId2.setForeground(new java.awt.Color(0, 0, 102));
        txtId2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtId2.setEnabled(false);
        txtId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId2ActionPerformed(evt);
            }
        });
        jPanel3.add(txtId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 70, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 51));
        jLabel3.setText("idApContrato:");
        jLabel3.setToolTipText("");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, 20));

        txtId3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtId3.setForeground(new java.awt.Color(0, 0, 102));
        txtId3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtId3.setEnabled(false);
        txtId3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId3ActionPerformed(evt);
            }
        });
        jPanel3.add(txtId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 70, -1));

        txtRSocial.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtRSocial.setForeground(new java.awt.Color(0, 0, 102));
        txtRSocial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(txtRSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 120, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 51));
        jLabel4.setText("Peso:");
        jLabel4.setToolTipText("");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, 20));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 350, 230));

        txtId4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtId4.setForeground(new java.awt.Color(0, 0, 102));
        txtId4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtId4.setEnabled(false);
        txtId4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId4ActionPerformed(evt);
            }
        });
        jPanel2.add(txtId4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 110, 20));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 0, 51));
        jLabel23.setText("Total Aperturas:");
        jLabel23.setToolTipText("");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, 20));

        txtId5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtId5.setForeground(new java.awt.Color(0, 0, 102));
        txtId5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtId5.setEnabled(false);
        txtId5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId5ActionPerformed(evt);
            }
        });
        jPanel2.add(txtId5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 110, 20));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 0, 51));
        jLabel24.setText("Total Comprado:");
        jLabel24.setToolTipText("");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, 20));

        txtId6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtId6.setForeground(new java.awt.Color(0, 0, 102));
        txtId6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtId6.setEnabled(false);
        txtId6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId6ActionPerformed(evt);
            }
        });
        jPanel2.add(txtId6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 110, 20));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 0, 51));
        jLabel27.setText("Total Faltante:");
        jLabel27.setToolTipText("");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 780, 590));
        jPanel2.getAccessibleContext().setAccessibleName("Mantenimiento de Compra Contrato");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRO COMPRA CONTRATO");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 800, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId1ActionPerformed

    private void txtId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId2ActionPerformed

    private void btnEditar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar2ActionPerformed

    private void btnNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevo1ActionPerformed

    private void txtId3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId3ActionPerformed

    private void txtId4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId4ActionPerformed

    private void txtId5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId5ActionPerformed

    private void txtId6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEditar2;
    public javax.swing.JButton btnNuevo1;
    public javax.swing.JButton btnRegistrar;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JComboBox<String> jcbEstado;
    public javax.swing.JTable jtAperturaContrato;
    public javax.swing.JTable jtEmpresa;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtId1;
    public javax.swing.JTextField txtId2;
    public javax.swing.JTextField txtId3;
    public javax.swing.JTextField txtId4;
    public javax.swing.JTextField txtId5;
    public javax.swing.JTextField txtId6;
    public javax.swing.JTextField txtRSocial;
    public javax.swing.JTextField txtRSocial1;
    public javax.swing.JTextField txtRSocial2;
    // End of variables declaration//GEN-END:variables
}
