/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author MustainE
 */
public class RCompraContrato extends javax.swing.JInternalFrame {

    public RCompraContrato() {
        initComponents();
        btnRegistrar.setEnabled(false);
        //btnNuevo.setEnabled(true);
        txtTcompraContrato.setEnabled(false);
        txtPeso.setEnabled(false);
        txtPrecio.setEnabled(false);
        txtImptotal.setEnabled(false);
        jdFecha.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtTcompraContrato = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCompraContrato = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        txtRSocial2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtAperturaContrato = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        txtTfaltantecomp = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jcbEstado = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        txtImptotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jdFecha = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtIdCC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdApc = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        txtTotalApc = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtTComprado = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtTFaltante = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 0, 51));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("..Registro Tipo Documento..");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 51), 1, true), "Mantenimiento de Apertura Contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(153, 0, 51))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(153, 0, 51));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTcompraContrato.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtTcompraContrato.setForeground(new java.awt.Color(255, 255, 255));
        txtTcompraContrato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtTcompraContrato.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtTcompraContrato.setEnabled(false);
        txtTcompraContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTcompraContratoActionPerformed(evt);
            }
        });
        jPanel2.add(txtTcompraContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 110, 20));

        jtCompraContrato.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtCompraContrato.setForeground(new java.awt.Color(51, 51, 255));
        jtCompraContrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtCompraContrato.setGridColor(new java.awt.Color(0, 51, 153));
        jScrollPane1.setViewportView(jtCompraContrato);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 400, 230));

        jSeparator1.setForeground(new java.awt.Color(153, 0, 51));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 750, 10));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 0, 51));
        jLabel22.setText("Falta Comprar:");
        jLabel22.setToolTipText("");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, -1, 20));

        txtRSocial2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtRSocial2.setForeground(new java.awt.Color(0, 0, 102));
        txtRSocial2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtRSocial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 360, 20));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 51));
        jLabel6.setText("Buscar Apertura Contrato:");
        jLabel6.setToolTipText("");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        jtAperturaContrato.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtAperturaContrato.setForeground(new java.awt.Color(51, 51, 255));
        jtAperturaContrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtAperturaContrato.setGridColor(new java.awt.Color(0, 51, 153));
        jScrollPane2.setViewportView(jtAperturaContrato);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 760, 220));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 0, 51));
        jLabel26.setText("Total Compra:");
        jLabel26.setToolTipText("");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, 20));

        txtTfaltantecomp.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtTfaltantecomp.setForeground(new java.awt.Color(255, 255, 255));
        txtTfaltantecomp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtTfaltantecomp.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtTfaltantecomp.setEnabled(false);
        txtTfaltantecomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTfaltantecompActionPerformed(evt);
            }
        });
        jPanel2.add(txtTfaltantecomp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 110, 20));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 51), 1, true), "Registro Compra Contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 11), new java.awt.Color(153, 0, 51))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcbEstado.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jcbEstado.setForeground(new java.awt.Color(0, 0, 153));
        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jcbEstado.setToolTipText("");
        jcbEstado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel3.add(jcbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 150, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 0, 51));
        jLabel19.setText("Estado:");
        jLabel19.setToolTipText("");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        txtImptotal.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtImptotal.setForeground(new java.awt.Color(255, 255, 255));
        txtImptotal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtImptotal.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        jPanel3.add(txtImptotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 130, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 51));
        jLabel5.setText("Importe Total:");
        jLabel5.setToolTipText("");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        txtPrecio.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(0, 0, 102));
        txtPrecio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 90, -1));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 0, 51));
        jLabel25.setText("Precio:");
        jLabel25.setToolTipText("");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));
        jPanel3.add(jdFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 110, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 0, 51));
        jLabel21.setText("Fecha:");
        jLabel21.setToolTipText("");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("idCContrato:");
        jLabel1.setToolTipText("");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        txtIdCC.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtIdCC.setForeground(new java.awt.Color(0, 0, 102));
        txtIdCC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtIdCC.setEnabled(false);
        txtIdCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCCActionPerformed(evt);
            }
        });
        jPanel3.add(txtIdCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 70, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 51));
        jLabel3.setText("idApContrato:");
        jLabel3.setToolTipText("");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, 20));

        txtIdApc.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtIdApc.setForeground(new java.awt.Color(0, 0, 102));
        txtIdApc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtIdApc.setEnabled(false);
        txtIdApc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdApcActionPerformed(evt);
            }
        });
        jPanel3.add(txtIdApc, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 70, -1));

        txtPeso.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtPeso.setForeground(new java.awt.Color(0, 0, 102));
        txtPeso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 120, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 51));
        jLabel4.setText("Peso:");
        jLabel4.setToolTipText("");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, 20));

        btnRegistrar.setBackground(new java.awt.Color(0, 153, 153));
        btnRegistrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon("D:\\Sistema\\Imagenes\\icons8_Save_20px.png")); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 100, 30));

        btnNuevo.setBackground(new java.awt.Color(0, 153, 153));
        btnNuevo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setIcon(new javax.swing.ImageIcon("D:\\Sistema\\Imagenes\\icons8_Add_List_20px.png")); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel3.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 100, 30));

        btnEditar.setBackground(new java.awt.Color(0, 153, 153));
        btnEditar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon("D:\\Sistema\\Imagenes\\icons8_Edit_Property_20px.png")); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 100, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 350, 230));

        txtTotalApc.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtTotalApc.setForeground(new java.awt.Color(0, 0, 102));
        txtTotalApc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtTotalApc.setEnabled(false);
        txtTotalApc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalApcActionPerformed(evt);
            }
        });
        jPanel2.add(txtTotalApc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 110, 20));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 0, 51));
        jLabel23.setText("Total Aperturas:");
        jLabel23.setToolTipText("");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, 20));

        txtTComprado.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtTComprado.setForeground(new java.awt.Color(0, 0, 102));
        txtTComprado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtTComprado.setEnabled(false);
        txtTComprado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTCompradoActionPerformed(evt);
            }
        });
        jPanel2.add(txtTComprado, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 110, 20));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 0, 51));
        jLabel24.setText("Total Comprado:");
        jLabel24.setToolTipText("");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, 20));

        txtTFaltante.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtTFaltante.setForeground(new java.awt.Color(0, 0, 102));
        txtTFaltante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtTFaltante.setEnabled(false);
        txtTFaltante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTFaltanteActionPerformed(evt);
            }
        });
        jPanel2.add(txtTFaltante, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 110, 20));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 0, 51));
        jLabel27.setText("Total Faltante:");
        jLabel27.setToolTipText("");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 780, 590));
        jPanel2.getAccessibleContext().setAccessibleName("Mantenimiento de Compra Contrato");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRO COMPRA CONTRATO");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 800, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTcompraContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTcompraContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTcompraContratoActionPerformed

    private void txtTfaltantecompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTfaltantecompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTfaltantecompActionPerformed

    private void txtIdCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCCActionPerformed

    private void txtIdApcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdApcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdApcActionPerformed

    private void txtTotalApcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalApcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalApcActionPerformed

    private void txtTCompradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTCompradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTCompradoActionPerformed

    private void txtTFaltanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTFaltanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTFaltanteActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JComboBox<String> jcbEstado;
    public com.toedter.calendar.JDateChooser jdFecha;
    public javax.swing.JTable jtAperturaContrato;
    public javax.swing.JTable jtCompraContrato;
    public javax.swing.JTextField txtIdApc;
    public javax.swing.JTextField txtIdCC;
    public javax.swing.JTextField txtImptotal;
    public javax.swing.JTextField txtPeso;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JTextField txtRSocial2;
    public javax.swing.JTextField txtTComprado;
    public javax.swing.JTextField txtTFaltante;
    public javax.swing.JTextField txtTcompraContrato;
    public javax.swing.JTextField txtTfaltantecomp;
    public javax.swing.JTextField txtTotalApc;
    // End of variables declaration//GEN-END:variables
}
