/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author MustainE
 */
public class RDocutraza_Document extends javax.swing.JInternalFrame {

    public RDocutraza_Document() {
        initComponents();
        btnRegistrar.setEnabled(false);
        //btnNuevo.setEnabled(true);
        txtId.setEnabled(false);
        txtRSocial.setEnabled(false);
        //txtDireccion.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtEmpresa = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtEmpresa1 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        txtId1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jcbEstado = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId3 = new javax.swing.JTextField();
        txtRSocial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jcbEstado1 = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        txtDireccion1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtDireccion2 = new javax.swing.JTextField();
        jcbEstado2 = new javax.swing.JComboBox<>();
        txtRSocial3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRSocial4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtRSocial5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jcbEstado3 = new javax.swing.JComboBox<>();
        btnNuevo1 = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel32 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtId7 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtDireccion3 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtDireccion4 = new javax.swing.JTextField();
        jcbEstado6 = new javax.swing.JComboBox<>();
        jcbEstado7 = new javax.swing.JComboBox<>();
        btnNuevo2 = new javax.swing.JButton();
        btnRegistrar1 = new javax.swing.JButton();
        txtId8 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnEditar2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtEmpresa2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtEmpresa3 = new javax.swing.JTable();
        btnRegistrar2 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        txtId2 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtId9 = new javax.swing.JTextField();
        txtId10 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtId11 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        btnRegistrar3 = new javax.swing.JButton();
        btnEditar3 = new javax.swing.JButton();
        btnNuevo3 = new javax.swing.JButton();
        btnRegistrar4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 0, 51));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("..Registro Documento..");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 51), 1, true), "Mantenimiento de Apertura Contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(153, 0, 51))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(153, 0, 51));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtId.setForeground(new java.awt.Color(0, 0, 102));
        txtId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtId.setEnabled(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 670, 110, 20));

        jtEmpresa.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtEmpresa.setForeground(new java.awt.Color(51, 51, 255));
        jtEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtEmpresa.setGridColor(new java.awt.Color(0, 51, 153));
        jScrollPane1.setViewportView(jtEmpresa);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 1030, 320));

        jSeparator1.setForeground(new java.awt.Color(153, 0, 51));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 1510, 10));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 0, 51));
        jLabel22.setText("Falta Comprar:");
        jLabel22.setToolTipText("");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 670, -1, 20));

        jtEmpresa1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtEmpresa1.setForeground(new java.awt.Color(51, 51, 255));
        jtEmpresa1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtEmpresa1.setGridColor(new java.awt.Color(0, 51, 153));
        jScrollPane2.setViewportView(jtEmpresa1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 390, 250));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 0, 51));
        jLabel26.setText("Total Compra:");
        jLabel26.setToolTipText("");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 670, -1, 20));

        txtId1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtId1.setForeground(new java.awt.Color(0, 0, 102));
        txtId1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtId1.setEnabled(false);
        txtId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 670, 110, 20));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 51), 1, true), "Registro de control de trackinglist", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 11), new java.awt.Color(153, 0, 51))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcbEstado.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jcbEstado.setForeground(new java.awt.Color(0, 0, 153));
        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "wtorres" }));
        jcbEstado.setToolTipText("");
        jcbEstado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel3.add(jcbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 400, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 0, 51));
        jLabel19.setText("Estado:");
        jLabel19.setToolTipText("");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, 20));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 51));
        jLabel5.setText("Condicion:");
        jLabel5.setToolTipText("");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, 20));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 0, 51));
        jLabel25.setText("Certificado:");
        jLabel25.setToolTipText("");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));
        jPanel3.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 110, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 0, 51));
        jLabel21.setText("Fecha:");
        jLabel21.setToolTipText("");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 51));
        jLabel3.setText("idCContrato:");
        jLabel3.setToolTipText("");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        txtId3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtId3.setForeground(new java.awt.Color(0, 0, 102));
        txtId3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtId3.setEnabled(false);
        txtId3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId3ActionPerformed(evt);
            }
        });
        jPanel3.add(txtId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 70, -1));

        txtRSocial.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtRSocial.setForeground(new java.awt.Color(0, 0, 102));
        txtRSocial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(txtRSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 80, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 51));
        jLabel4.setText("KBruto:");
        jLabel4.setToolTipText("");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, 20));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 0, 51));
        jLabel28.setText("Cliente:");
        jLabel28.setToolTipText("");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        jcbEstado1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jcbEstado1.setForeground(new java.awt.Color(0, 0, 153));
        jcbEstado1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jcbEstado1.setToolTipText("");
        jcbEstado1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel3.add(jcbEstado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 150, -1));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 0, 51));
        jLabel29.setText("SerieGuia:");
        jLabel29.setToolTipText("");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        txtDireccion1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtDireccion1.setForeground(new java.awt.Color(0, 0, 102));
        txtDireccion1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(txtDireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 70, -1));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(153, 0, 51));
        jLabel30.setText("Correlativo:");
        jLabel30.setToolTipText("");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, 20));

        txtDireccion2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtDireccion2.setForeground(new java.awt.Color(0, 0, 102));
        txtDireccion2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(txtDireccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 90, -1));

        jcbEstado2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jcbEstado2.setForeground(new java.awt.Color(0, 0, 153));
        jcbEstado2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jcbEstado2.setToolTipText("");
        jcbEstado2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel3.add(jcbEstado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 150, -1));

        txtRSocial3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtRSocial3.setForeground(new java.awt.Color(0, 0, 102));
        txtRSocial3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(txtRSocial3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 60, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 51));
        jLabel7.setText("Sacos:");
        jLabel7.setToolTipText("");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        txtRSocial4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtRSocial4.setForeground(new java.awt.Color(0, 0, 102));
        txtRSocial4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(txtRSocial4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 80, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 51));
        jLabel8.setText("KNeto:");
        jLabel8.setToolTipText("");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, 20));

        txtRSocial5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtRSocial5.setForeground(new java.awt.Color(0, 0, 102));
        txtRSocial5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(txtRSocial5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 160, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 51));
        jLabel9.setText("Fairtrade:");
        jLabel9.setToolTipText("");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        jcbEstado3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jcbEstado3.setForeground(new java.awt.Color(0, 0, 153));
        jcbEstado3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jcbEstado3.setToolTipText("");
        jcbEstado3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel3.add(jcbEstado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 150, -1));

        btnNuevo1.setBackground(new java.awt.Color(153, 0, 51));
        btnNuevo1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNuevo1.setForeground(new java.awt.Color(0, 0, 153));
        btnNuevo1.setIcon(new javax.swing.ImageIcon("D:\\Sistema\\Imagenes\\icons8_Add_List_20px.png")); // NOI18N
        btnNuevo1.setText("Nuevo");
        btnNuevo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnNuevo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 100, 30));

        btnRegistrar.setBackground(new java.awt.Color(153, 0, 51));
        btnRegistrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 153));
        btnRegistrar.setIcon(new javax.swing.ImageIcon("D:\\Sistema\\Imagenes\\icons8_Save_20px.png")); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 100, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 470, 250));
        jPanel3.getAccessibleContext().setAccessibleName("Registro de control de trackinglist");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 51), 1, true), "Registro de Documentos Asociados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 11), new java.awt.Color(153, 0, 51))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 0, 51));
        jLabel20.setText("Estado:");
        jLabel20.setToolTipText("");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, 20));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(153, 0, 51));
        jLabel31.setText("Tipo Documento:");
        jLabel31.setToolTipText("");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));
        jPanel4.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 110, -1));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(153, 0, 51));
        jLabel32.setText("Fecha:");
        jLabel32.setToolTipText("");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 40, 20));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 51));
        jLabel11.setText("idDocumento:");
        jLabel11.setToolTipText("");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        txtId7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtId7.setForeground(new java.awt.Color(0, 0, 102));
        txtId7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtId7.setEnabled(false);
        txtId7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId7ActionPerformed(evt);
            }
        });
        jPanel4.add(txtId7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 50, -1));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(153, 0, 51));
        jLabel34.setText("Serie:");
        jLabel34.setToolTipText("");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        txtDireccion3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtDireccion3.setForeground(new java.awt.Color(0, 0, 102));
        txtDireccion3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(txtDireccion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 70, -1));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(153, 0, 51));
        jLabel35.setText("Correlativo:");
        jLabel35.setToolTipText("");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, 20));

        txtDireccion4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtDireccion4.setForeground(new java.awt.Color(0, 0, 102));
        txtDireccion4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(txtDireccion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 90, -1));

        jcbEstado6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jcbEstado6.setForeground(new java.awt.Color(0, 0, 153));
        jcbEstado6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jcbEstado6.setToolTipText("");
        jcbEstado6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel4.add(jcbEstado6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 110, -1));

        jcbEstado7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jcbEstado7.setForeground(new java.awt.Color(0, 0, 153));
        jcbEstado7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jcbEstado7.setToolTipText("");
        jcbEstado7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel4.add(jcbEstado7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 150, -1));

        btnNuevo2.setBackground(new java.awt.Color(153, 0, 51));
        btnNuevo2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNuevo2.setForeground(new java.awt.Color(0, 0, 153));
        btnNuevo2.setIcon(new javax.swing.ImageIcon("D:\\Sistema\\Imagenes\\icons8_Add_List_20px.png")); // NOI18N
        btnNuevo2.setText("Nuevo");
        btnNuevo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnNuevo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnNuevo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 100, 30));

        btnRegistrar1.setBackground(new java.awt.Color(153, 0, 51));
        btnRegistrar1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRegistrar1.setForeground(new java.awt.Color(0, 0, 153));
        btnRegistrar1.setIcon(new javax.swing.ImageIcon("D:\\Sistema\\Imagenes\\icons8_Save_20px.png")); // NOI18N
        btnRegistrar1.setText("Registrar");
        btnRegistrar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 100, 30));

        txtId8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtId8.setForeground(new java.awt.Color(0, 0, 102));
        txtId8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtId8.setEnabled(false);
        txtId8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId8ActionPerformed(evt);
            }
        });
        jPanel4.add(txtId8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 50, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 0, 51));
        jLabel16.setText("idDocuTraza:");
        jLabel16.setToolTipText("");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, 20));

        btnEditar2.setBackground(new java.awt.Color(153, 0, 51));
        btnEditar2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEditar2.setForeground(new java.awt.Color(0, 0, 153));
        btnEditar2.setIcon(new javax.swing.ImageIcon("D:\\Sistema\\Imagenes\\icons8_Edit_Property_20px.png")); // NOI18N
        btnEditar2.setText("Editar");
        btnEditar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnEditar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnEditar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 100, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 470, 470, 190));

        jtEmpresa2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtEmpresa2.setForeground(new java.awt.Color(51, 51, 255));
        jtEmpresa2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtEmpresa2.setGridColor(new java.awt.Color(0, 51, 153));
        jScrollPane3.setViewportView(jtEmpresa2);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 630, 240));

        jtEmpresa3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtEmpresa3.setForeground(new java.awt.Color(51, 51, 255));
        jtEmpresa3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtEmpresa3.setGridColor(new java.awt.Color(0, 51, 153));
        jScrollPane4.setViewportView(jtEmpresa3);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 290, 470, 170));

        btnRegistrar2.setBackground(new java.awt.Color(153, 0, 51));
        btnRegistrar2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRegistrar2.setForeground(new java.awt.Color(0, 0, 153));
        btnRegistrar2.setIcon(new javax.swing.ImageIcon("D:\\Sistema\\Imagenes\\icons8_Save_20px.png")); // NOI18N
        btnRegistrar2.setText("Excel");
        btnRegistrar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnRegistrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, 100, 30));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(153, 0, 51));
        jLabel33.setText("Total Compra:");
        jLabel33.setToolTipText("");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 20));

        txtId2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtId2.setForeground(new java.awt.Color(0, 0, 102));
        txtId2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtId2.setEnabled(false);
        txtId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId2ActionPerformed(evt);
            }
        });
        jPanel2.add(txtId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 110, 20));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(153, 0, 51));
        jLabel36.setText("Falta Comprar:");
        jLabel36.setToolTipText("");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, 20));

        txtId9.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtId9.setForeground(new java.awt.Color(0, 0, 102));
        txtId9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtId9.setEnabled(false);
        txtId9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId9ActionPerformed(evt);
            }
        });
        jPanel2.add(txtId9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 110, 20));

        txtId10.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtId10.setForeground(new java.awt.Color(0, 0, 102));
        txtId10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtId10.setEnabled(false);
        txtId10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId10ActionPerformed(evt);
            }
        });
        jPanel2.add(txtId10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 110, 20));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(153, 0, 51));
        jLabel37.setText("Falta Comprar:");
        jLabel37.setToolTipText("");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, 20));

        txtId11.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtId11.setForeground(new java.awt.Color(0, 0, 102));
        txtId11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtId11.setEnabled(false);
        txtId11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId11ActionPerformed(evt);
            }
        });
        jPanel2.add(txtId11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 110, 20));

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(153, 0, 51));
        jLabel38.setText("Falta Comprar:");
        jLabel38.setToolTipText("");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, -1, 20));

        btnRegistrar3.setBackground(new java.awt.Color(153, 0, 51));
        btnRegistrar3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRegistrar3.setForeground(new java.awt.Color(0, 0, 153));
        btnRegistrar3.setIcon(new javax.swing.ImageIcon("D:\\Sistema\\Imagenes\\icons8_Save_20px.png")); // NOI18N
        btnRegistrar3.setText("Registrar");
        btnRegistrar3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnRegistrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 660, 100, 40));

        btnEditar3.setBackground(new java.awt.Color(153, 0, 51));
        btnEditar3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEditar3.setForeground(new java.awt.Color(0, 0, 153));
        btnEditar3.setIcon(new javax.swing.ImageIcon("D:\\Sistema\\Imagenes\\icons8_Edit_Property_20px.png")); // NOI18N
        btnEditar3.setText("Editar");
        btnEditar3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnEditar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 660, 100, 40));

        btnNuevo3.setBackground(new java.awt.Color(153, 0, 51));
        btnNuevo3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNuevo3.setForeground(new java.awt.Color(0, 0, 153));
        btnNuevo3.setIcon(new javax.swing.ImageIcon("D:\\Sistema\\Imagenes\\icons8_Add_List_20px.png")); // NOI18N
        btnNuevo3.setText("Nuevo");
        btnNuevo3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnNuevo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 660, 100, 40));

        btnRegistrar4.setBackground(new java.awt.Color(153, 0, 51));
        btnRegistrar4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRegistrar4.setForeground(new java.awt.Color(0, 0, 153));
        btnRegistrar4.setIcon(new javax.swing.ImageIcon("D:\\Sistema\\Imagenes\\icons8_Save_20px.png")); // NOI18N
        btnRegistrar4.setText("Procesar");
        btnRegistrar4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnRegistrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, 100, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1530, 710));
        jPanel2.getAccessibleContext().setAccessibleName("Mantenimiento de Compra Contrato");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRO DE CONTROL DE TRACKINGLIST");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1550, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId1ActionPerformed

    private void btnEditar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar2ActionPerformed

    private void btnNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevo1ActionPerformed

    private void txtId3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId3ActionPerformed

    private void btnRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrar1ActionPerformed

    private void btnNuevo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevo2ActionPerformed

    private void txtId7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId7ActionPerformed

    private void txtId8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId8ActionPerformed

    private void btnRegistrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrar2ActionPerformed

    private void txtId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId2ActionPerformed

    private void txtId9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId9ActionPerformed

    private void txtId10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId10ActionPerformed

    private void txtId11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId11ActionPerformed

    private void btnRegistrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrar3ActionPerformed

    private void btnEditar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar3ActionPerformed

    private void btnNuevo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevo3ActionPerformed

    private void btnRegistrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrar4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEditar2;
    public javax.swing.JButton btnEditar3;
    public javax.swing.JButton btnNuevo1;
    public javax.swing.JButton btnNuevo2;
    public javax.swing.JButton btnNuevo3;
    public javax.swing.JButton btnRegistrar;
    public javax.swing.JButton btnRegistrar1;
    public javax.swing.JButton btnRegistrar2;
    public javax.swing.JButton btnRegistrar3;
    public javax.swing.JButton btnRegistrar4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JComboBox<String> jcbEstado;
    public javax.swing.JComboBox<String> jcbEstado1;
    public javax.swing.JComboBox<String> jcbEstado2;
    public javax.swing.JComboBox<String> jcbEstado3;
    public javax.swing.JComboBox<String> jcbEstado6;
    public javax.swing.JComboBox<String> jcbEstado7;
    public javax.swing.JTable jtEmpresa;
    public javax.swing.JTable jtEmpresa1;
    public javax.swing.JTable jtEmpresa2;
    public javax.swing.JTable jtEmpresa3;
    public javax.swing.JTextField txtDireccion1;
    public javax.swing.JTextField txtDireccion2;
    public javax.swing.JTextField txtDireccion3;
    public javax.swing.JTextField txtDireccion4;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtId1;
    public javax.swing.JTextField txtId10;
    public javax.swing.JTextField txtId11;
    public javax.swing.JTextField txtId2;
    public javax.swing.JTextField txtId3;
    public javax.swing.JTextField txtId7;
    public javax.swing.JTextField txtId8;
    public javax.swing.JTextField txtId9;
    public javax.swing.JTextField txtRSocial;
    public javax.swing.JTextField txtRSocial3;
    public javax.swing.JTextField txtRSocial4;
    public javax.swing.JTextField txtRSocial5;
    // End of variables declaration//GEN-END:variables
}
