/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author MustainE
 */
public class RPersonaUsuario extends javax.swing.JInternalFrame {

    public RPersonaUsuario() {
        initComponents();
        btnRegistrar.setEnabled(false);
        btnNuevo.setEnabled(true);
        txtIdpersona.setEnabled(false);
        txtRSocial.setEnabled(false);
        txtCiudad.setEnabled(false);
        txtDireccion.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdpersona = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPersona = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtCiudad = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtRSocial = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jcbTipoUsuario = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtDistrito = new javax.swing.JTextField();
        txtRucDni = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox<>();
        txtNombres = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtProvincia = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        txtCodAgricultor = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtBPersona = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtCafePractice = new javax.swing.JTextField();
        txtOrga = new javax.swing.JTextField();
        txtCp = new javax.swing.JTextField();
        txtFinca = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jRPPassword = new jpass.JRPasswordField();
        jLabel36 = new javax.swing.JLabel();
        jcbPersona = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtAnexo = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jYcEjercicio = new com.toedter.calendar.JYearChooser();
        txtCelular = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 0, 51));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("..Registro Persona..");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 51), 1, true), "Mantenimiento de Empresa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(153, 0, 51))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(153, 0, 51));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("IdPersona:");
        jLabel1.setToolTipText("");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 51));
        jLabel4.setText("Razon Social:");
        jLabel4.setToolTipText("");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        txtIdpersona.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtIdpersona.setForeground(new java.awt.Color(153, 0, 51));
        txtIdpersona.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtIdpersona.setEnabled(false);
        txtIdpersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdpersonaActionPerformed(evt);
            }
        });
        jPanel2.add(txtIdpersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 40, 20));

        jtPersona.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtPersona.setForeground(new java.awt.Color(51, 51, 255));
        jtPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtPersona.setGridColor(new java.awt.Color(0, 51, 153));
        jScrollPane1.setViewportView(jtPersona);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 690, 280));

        btnEditar.setBackground(new java.awt.Color(204, 204, 255));
        btnEditar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(0, 0, 153));
        btnEditar.setIcon(new javax.swing.ImageIcon("D:\\Sistema\\Imagenes\\icons8_Edit_Property_20px.png")); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 620, 100, 30));

        jSeparator1.setForeground(new java.awt.Color(153, 0, 51));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 690, 10));

        txtCiudad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCiudad.setForeground(new java.awt.Color(153, 0, 51));
        txtCiudad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 230, 20));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 0, 51));
        jLabel19.setText("Estado:");
        jLabel19.setToolTipText("");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, 20));

        txtDireccion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(153, 0, 51));
        txtDireccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 330, 20));

        txtRSocial.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRSocial.setForeground(new java.awt.Color(153, 0, 51));
        txtRSocial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtRSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 310, 20));

        btnNuevo.setBackground(new java.awt.Color(204, 204, 255));
        btnNuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(0, 0, 153));
        btnNuevo.setIcon(new javax.swing.ImageIcon("D:\\Sistema\\Imagenes\\icons8_Add_List_20px.png")); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 620, 100, 30));

        btnRegistrar.setBackground(new java.awt.Color(204, 204, 255));
        btnRegistrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 153));
        btnRegistrar.setIcon(new javax.swing.ImageIcon("D:\\Sistema\\Imagenes\\icons8_Save_20px.png")); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 620, 100, 30));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 0, 51));
        jLabel20.setText("Tipo Persona:");
        jLabel20.setToolTipText("");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 20));

        jcbTipoUsuario.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jcbTipoUsuario.setForeground(new java.awt.Color(0, 0, 153));
        jcbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agricultor", "Cliente", "Proveedor", "Tercero", "Empleado" }));
        jcbTipoUsuario.setToolTipText("");
        jcbTipoUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel2.add(jcbTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 100, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 0, 51));
        jLabel21.setText("Dirección:");
        jLabel21.setToolTipText("");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 0, 51));
        jLabel22.setText("Distrito:");
        jLabel22.setToolTipText("");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, 20));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 0, 51));
        jLabel23.setText("Ruc/Dni:");
        jLabel23.setToolTipText("");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 50, 20));

        txtDistrito.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtDistrito.setForeground(new java.awt.Color(153, 0, 51));
        txtDistrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 230, 20));

        txtRucDni.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRucDni.setForeground(new java.awt.Color(153, 0, 51));
        txtRucDni.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtRucDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 190, 20));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 0, 51));
        jLabel24.setText("Ciudad:");
        jLabel24.setToolTipText("");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, 20));

        jcbEstado.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jcbEstado.setForeground(new java.awt.Color(0, 0, 153));
        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--", "Activo", "Inactivo" }));
        jcbEstado.setToolTipText("");
        jcbEstado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel2.add(jcbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 110, 20));

        txtNombres.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNombres.setForeground(new java.awt.Color(153, 0, 51));
        txtNombres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 330, 20));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 51));
        jLabel14.setText("Nombres:");
        jLabel14.setToolTipText("");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        txtApellidos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtApellidos.setForeground(new java.awt.Color(153, 0, 51));
        txtApellidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 230, 20));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 0, 51));
        jLabel15.setText("Apellidos:");
        jLabel15.setToolTipText("");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, 20));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 0, 51));
        jLabel25.setText("Provincia: ");
        jLabel25.setToolTipText("");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        txtProvincia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtProvincia.setForeground(new java.awt.Color(153, 0, 51));
        txtProvincia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 330, 20));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 0, 51));
        jLabel26.setText("Pais: ");
        jLabel26.setToolTipText("");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 20));

        txtPais.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPais.setForeground(new java.awt.Color(153, 0, 51));
        txtPais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 120, 20));

        txtCodAgricultor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCodAgricultor.setForeground(new java.awt.Color(153, 0, 51));
        txtCodAgricultor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtCodAgricultor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 100, 20));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 0, 51));
        jLabel27.setText("Finca:");
        jLabel27.setToolTipText("");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, 20));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 0, 51));
        jLabel28.setText("CodAgricultor:");
        jLabel28.setToolTipText("");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 20));

        txtBPersona.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtBPersona.setForeground(new java.awt.Color(153, 0, 51));
        txtBPersona.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtBPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 420, 20));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 0, 51));
        jLabel29.setText("Anexo:");
        jLabel29.setToolTipText("");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(153, 0, 51));
        jLabel30.setText("Correo Electronico:");
        jLabel30.setToolTipText("");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, 20));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(153, 0, 51));
        jLabel31.setText("idOrga:");
        jLabel31.setToolTipText("");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, 20));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(153, 0, 51));
        jLabel32.setText("idCP:");
        jLabel32.setToolTipText("");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, 20));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(153, 0, 51));
        jLabel33.setText("idCafePractice:");
        jLabel33.setToolTipText("");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, 20));

        txtCorreo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(153, 0, 51));
        txtCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 230, 20));

        txtCafePractice.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCafePractice.setForeground(new java.awt.Color(153, 0, 51));
        txtCafePractice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCafePractice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCafePracticeActionPerformed(evt);
            }
        });
        jPanel2.add(txtCafePractice, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 110, 20));

        txtOrga.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtOrga.setForeground(new java.awt.Color(153, 0, 51));
        txtOrga.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtOrga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrgaActionPerformed(evt);
            }
        });
        jPanel2.add(txtOrga, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 100, 20));

        txtCp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCp.setForeground(new java.awt.Color(153, 0, 51));
        txtCp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpActionPerformed(evt);
            }
        });
        jPanel2.add(txtCp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 100, 20));

        txtFinca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtFinca.setForeground(new java.awt.Color(153, 0, 51));
        txtFinca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtFinca, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 210, 20));

        txtUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(153, 0, 51));
        txtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 120, 20));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(153, 0, 51));
        jLabel35.setText("Contraseña:");
        jLabel35.setToolTipText("");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, 20));
        jPanel2.add(jRPPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 130, 20));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(153, 0, 51));
        jLabel36.setText("Tipo Usuario:");
        jLabel36.setToolTipText("");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, 20));

        jcbPersona.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jcbPersona.setForeground(new java.awt.Color(0, 0, 153));
        jcbPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Natural", "Juridico" }));
        jcbPersona.setToolTipText("");
        jcbPersona.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel2.add(jcbPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 150, 20));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(153, 0, 51));
        jLabel37.setText("Buscador segun dato coincidente:");
        jLabel37.setToolTipText("");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 20));

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(153, 0, 51));
        jLabel38.setText("Usuario:");
        jLabel38.setToolTipText("");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 20));

        txtAnexo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtAnexo.setForeground(new java.awt.Color(153, 0, 51));
        txtAnexo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtAnexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 230, 20));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(153, 0, 51));
        jLabel34.setText("Ejercicio/Año:");
        jLabel34.setToolTipText("");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, 20));
        jPanel2.add(jYcEjercicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 60, -1));

        txtCelular.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCelular.setForeground(new java.awt.Color(153, 0, 51));
        txtCelular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });
        jPanel2.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 100, 20));

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(153, 0, 51));
        jLabel39.setText("Celular:");
        jLabel39.setToolTipText("");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 710, 660));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRO DE PERSONA");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 730, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtIdpersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdpersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdpersonaActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtCafePracticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCafePracticeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCafePracticeActionPerformed

    private void txtOrgaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrgaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrgaActionPerformed

    private void txtCpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public jpass.JRPasswordField jRPPassword;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public com.toedter.calendar.JYearChooser jYcEjercicio;
    public javax.swing.JComboBox<String> jcbEstado;
    public javax.swing.JComboBox<String> jcbPersona;
    public javax.swing.JComboBox<String> jcbTipoUsuario;
    public javax.swing.JTable jtPersona;
    public javax.swing.JTextField txtAnexo;
    public javax.swing.JTextField txtApellidos;
    public javax.swing.JTextField txtBPersona;
    public javax.swing.JTextField txtCafePractice;
    public javax.swing.JTextField txtCelular;
    public javax.swing.JTextField txtCiudad;
    public javax.swing.JTextField txtCodAgricultor;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtCp;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtDistrito;
    public javax.swing.JTextField txtFinca;
    public javax.swing.JTextField txtIdpersona;
    public javax.swing.JTextField txtNombres;
    public javax.swing.JTextField txtOrga;
    public javax.swing.JTextField txtPais;
    public javax.swing.JTextField txtProvincia;
    public javax.swing.JTextField txtRSocial;
    public javax.swing.JTextField txtRucDni;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
