/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author MustainE
 */
public class RPersonaUsuario extends javax.swing.JInternalFrame {

    public RPersonaUsuario() {
        initComponents();
        btnRegistrar.setEnabled(false);
        btnNuevo.setEnabled(true);
        txtId.setEnabled(false);
        txtRSocial.setEnabled(false);
        txtRuc.setEnabled(false);
        txtDireccion.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtEmpresa = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtRuc = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtRSocial = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtRuc2 = new javax.swing.JTextField();
        txtRuc3 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jcbEstado1 = new javax.swing.JComboBox<>();
        txtRuc5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtRuc6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtRuc1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtRuc7 = new javax.swing.JTextField();
        txtRuc8 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtRuc9 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtRuc10 = new javax.swing.JTextField();
        txtRuc11 = new javax.swing.JTextField();
        txtRuc12 = new javax.swing.JTextField();
        txtRuc13 = new javax.swing.JTextField();
        txtRuc14 = new javax.swing.JTextField();
        txtRuc15 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jRPasswordField1 = new jpass.JRPasswordField();
        jLabel36 = new javax.swing.JLabel();
        jcbEstado2 = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtRuc16 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 0, 51));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("..Registro Persona..");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 51), 1, true), "Mantenimiento de Empresa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(153, 0, 51))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(153, 0, 51));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("IdPersona:");
        jLabel1.setToolTipText("");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 51));
        jLabel4.setText("Razon Social:");
        jLabel4.setToolTipText("");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        txtId.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtId.setForeground(new java.awt.Color(153, 0, 51));
        txtId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtId.setEnabled(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 90, 20));

        jtEmpresa.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtEmpresa.setForeground(new java.awt.Color(51, 51, 255));
        jtEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtEmpresa.setGridColor(new java.awt.Color(0, 51, 153));
        jScrollPane1.setViewportView(jtEmpresa);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 690, 280));

        btnEditar.setBackground(new java.awt.Color(204, 204, 255));
        btnEditar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(0, 0, 153));
        btnEditar.setIcon(new javax.swing.ImageIcon("D:\\Sistema\\Imagenes\\icons8_Edit_Property_20px.png")); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 620, 100, 30));

        jSeparator1.setForeground(new java.awt.Color(153, 0, 51));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 690, 10));

        txtRuc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRuc.setForeground(new java.awt.Color(153, 0, 51));
        txtRuc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 230, 20));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 0, 51));
        jLabel19.setText("Estado:");
        jLabel19.setToolTipText("");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, 20));

        txtDireccion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(153, 0, 51));
        txtDireccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 330, 20));

        txtRSocial.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRSocial.setForeground(new java.awt.Color(153, 0, 51));
        txtRSocial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtRSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 310, 20));

        btnNuevo.setBackground(new java.awt.Color(204, 204, 255));
        btnNuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(0, 0, 153));
        btnNuevo.setIcon(new javax.swing.ImageIcon("D:\\Sistema\\Imagenes\\icons8_Add_List_20px.png")); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 620, 100, 30));

        btnRegistrar.setBackground(new java.awt.Color(204, 204, 255));
        btnRegistrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 153));
        btnRegistrar.setIcon(new javax.swing.ImageIcon("D:\\Sistema\\Imagenes\\icons8_Save_20px.png")); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 620, 100, 30));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 0, 51));
        jLabel20.setText("Tipo Persona:");
        jLabel20.setToolTipText("");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, 20));

        jcbEstado.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jcbEstado.setForeground(new java.awt.Color(0, 0, 153));
        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--", "Empleado", "Administrador", "Cliente", "Agricultor" }));
        jcbEstado.setToolTipText("");
        jcbEstado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel2.add(jcbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 200, 20));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 0, 51));
        jLabel21.setText("Dirección:");
        jLabel21.setToolTipText("");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 0, 51));
        jLabel22.setText("Distrito:");
        jLabel22.setToolTipText("");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, 20));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 0, 51));
        jLabel23.setText("Ruc/Dni:");
        jLabel23.setToolTipText("");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 50, 20));

        txtRuc2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRuc2.setForeground(new java.awt.Color(153, 0, 51));
        txtRuc2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtRuc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 230, 20));

        txtRuc3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRuc3.setForeground(new java.awt.Color(153, 0, 51));
        txtRuc3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtRuc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 190, 20));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 0, 51));
        jLabel24.setText("Ciudad:");
        jLabel24.setToolTipText("");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, 20));

        jcbEstado1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jcbEstado1.setForeground(new java.awt.Color(0, 0, 153));
        jcbEstado1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--", "Activo", "Inactivo" }));
        jcbEstado1.setToolTipText("");
        jcbEstado1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel2.add(jcbEstado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 150, 20));

        txtRuc5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRuc5.setForeground(new java.awt.Color(153, 0, 51));
        txtRuc5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtRuc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 330, 20));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 51));
        jLabel14.setText("Nombres:");
        jLabel14.setToolTipText("");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        txtRuc6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRuc6.setForeground(new java.awt.Color(153, 0, 51));
        txtRuc6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtRuc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 230, 20));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 0, 51));
        jLabel15.setText("Apellidos:");
        jLabel15.setToolTipText("");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, 20));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 0, 51));
        jLabel25.setText("Provincia: ");
        jLabel25.setToolTipText("");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        txtRuc1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRuc1.setForeground(new java.awt.Color(153, 0, 51));
        txtRuc1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtRuc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 330, 20));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 0, 51));
        jLabel26.setText("Pais: ");
        jLabel26.setToolTipText("");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 20));

        txtRuc7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRuc7.setForeground(new java.awt.Color(153, 0, 51));
        txtRuc7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtRuc7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 120, 20));

        txtRuc8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRuc8.setForeground(new java.awt.Color(153, 0, 51));
        txtRuc8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtRuc8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 100, 20));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 0, 51));
        jLabel27.setText("Finca:");
        jLabel27.setToolTipText("");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, 20));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 0, 51));
        jLabel28.setText("CodAgricultor:");
        jLabel28.setToolTipText("");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 20));

        txtRuc9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRuc9.setForeground(new java.awt.Color(153, 0, 51));
        txtRuc9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtRuc9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 420, 20));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 0, 51));
        jLabel29.setText("Anexo:");
        jLabel29.setToolTipText("");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(153, 0, 51));
        jLabel30.setText("Correo Electronico:");
        jLabel30.setToolTipText("");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, 20));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(153, 0, 51));
        jLabel31.setText("idOrga:");
        jLabel31.setToolTipText("");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, 20));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(153, 0, 51));
        jLabel32.setText("idCP:");
        jLabel32.setToolTipText("");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, 20));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(153, 0, 51));
        jLabel33.setText("idCafePractice:");
        jLabel33.setToolTipText("");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, 20));

        txtRuc10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRuc10.setForeground(new java.awt.Color(153, 0, 51));
        txtRuc10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtRuc10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 230, 20));

        txtRuc11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRuc11.setForeground(new java.awt.Color(153, 0, 51));
        txtRuc11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtRuc11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuc11ActionPerformed(evt);
            }
        });
        jPanel2.add(txtRuc11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 110, 20));

        txtRuc12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRuc12.setForeground(new java.awt.Color(153, 0, 51));
        txtRuc12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtRuc12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuc12ActionPerformed(evt);
            }
        });
        jPanel2.add(txtRuc12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 100, 20));

        txtRuc13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRuc13.setForeground(new java.awt.Color(153, 0, 51));
        txtRuc13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtRuc13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuc13ActionPerformed(evt);
            }
        });
        jPanel2.add(txtRuc13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 100, 20));

        txtRuc14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRuc14.setForeground(new java.awt.Color(153, 0, 51));
        txtRuc14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtRuc14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 210, 20));

        txtRuc15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRuc15.setForeground(new java.awt.Color(153, 0, 51));
        txtRuc15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtRuc15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuc15ActionPerformed(evt);
            }
        });
        jPanel2.add(txtRuc15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 120, 20));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(153, 0, 51));
        jLabel35.setText("Contraseña:");
        jLabel35.setToolTipText("");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, 20));
        jPanel2.add(jRPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 130, 20));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(153, 0, 51));
        jLabel36.setText("Tipo Usuario:");
        jLabel36.setToolTipText("");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, 20));

        jcbEstado2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jcbEstado2.setForeground(new java.awt.Color(0, 0, 153));
        jcbEstado2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--", "Empleado", "Administrador", "Cliente", "Agricultor" }));
        jcbEstado2.setToolTipText("");
        jcbEstado2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel2.add(jcbEstado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 150, 20));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(153, 0, 51));
        jLabel37.setText("Buscador segun dato coincidente:");
        jLabel37.setToolTipText("");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 20));

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(153, 0, 51));
        jLabel38.setText("Usuario:");
        jLabel38.setToolTipText("");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 20));

        txtRuc16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRuc16.setForeground(new java.awt.Color(153, 0, 51));
        txtRuc16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtRuc16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 230, 20));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(153, 0, 51));
        jLabel34.setText("Ejercicio/Año:");
        jLabel34.setToolTipText("");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, 20));
        jPanel2.add(jYearChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 60, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 710, 660));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRO DE PERSONA");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 730, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtRuc11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuc11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuc11ActionPerformed

    private void txtRuc12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuc12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuc12ActionPerformed

    private void txtRuc13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuc13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuc13ActionPerformed

    private void txtRuc15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuc15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuc15ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private jpass.JRPasswordField jRPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    public javax.swing.JComboBox<String> jcbEstado;
    public javax.swing.JComboBox<String> jcbEstado1;
    public javax.swing.JComboBox<String> jcbEstado2;
    public javax.swing.JTable jtEmpresa;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtRSocial;
    public javax.swing.JTextField txtRuc;
    public javax.swing.JTextField txtRuc1;
    public javax.swing.JTextField txtRuc10;
    public javax.swing.JTextField txtRuc11;
    public javax.swing.JTextField txtRuc12;
    public javax.swing.JTextField txtRuc13;
    public javax.swing.JTextField txtRuc14;
    public javax.swing.JTextField txtRuc15;
    public javax.swing.JTextField txtRuc16;
    public javax.swing.JTextField txtRuc2;
    public javax.swing.JTextField txtRuc3;
    public javax.swing.JTextField txtRuc5;
    public javax.swing.JTextField txtRuc6;
    public javax.swing.JTextField txtRuc7;
    public javax.swing.JTextField txtRuc8;
    public javax.swing.JTextField txtRuc9;
    // End of variables declaration//GEN-END:variables
}
