/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.ConformacionDao;
import dao.ListaCombosDao;
import javax.swing.DefaultComboBoxModel;
import modelo.ListaAgricultores;
import modelo.ListaCombos;

/**
 *
 * @author MustainE
 */
public class RPEstimado extends javax.swing.JInternalFrame {

    public RPEstimado() {
        initComponents();     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdEmp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtIdPerLPAEst = new javax.swing.JTextField();
        txtSerieGuia = new javax.swing.JTextField();
        jcbEstado = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txtDniRuc = new javax.swing.JTextField();
        txtCPDisp = new javax.swing.JTextField();
        txtCertificado = new javax.swing.JTextField();
        txtIdSuc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdCC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCorrelativo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtNomLPAEst = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtCodPro = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtNomPro = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtIdPersona = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtIdCpPro = new javax.swing.JTextField();
        txtIdOrgaPro = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtORGDisp = new javax.swing.JTextField();
        txtFTDisp = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtRainfDisp = new javax.swing.JTextField();
        txtConvDisp = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtKb = new javax.swing.JTextField();
        txtSacos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTara = new javax.swing.JTextField();
        txtKN = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtLiqCompra = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtGuia = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtImpTotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtFecha = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        txtIdProLPACon = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtNomLPACon = new javax.swing.JTextField();
        btnBuscarPro = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtIdDetDoc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtIdDocT = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 0, 51));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("..Actualizar Conformación Proveedor..");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PROVEEDOR CONFORMACIÓN");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 540, 20));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 51), 1, true), "Mantenimiento de Empresa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(153, 0, 51))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(153, 0, 51));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setBackground(new java.awt.Color(0, 153, 153));
        btnRegistrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon("D:\\Sistema\\Imagenes\\icons8_Save_20px.png")); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 100, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("IdEmp:");
        jLabel1.setToolTipText("");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 20, 40, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 51));
        jLabel4.setText("SerieGuia:");
        jLabel4.setToolTipText("");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        txtIdEmp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtIdEmp.setForeground(new java.awt.Color(0, 102, 102));
        txtIdEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtIdEmp.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtIdEmp.setEnabled(false);
        txtIdEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEmpActionPerformed(evt);
            }
        });
        jPanel2.add(txtIdEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 50, 20));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 0, 51));
        jLabel13.setText("Certificado:");
        jLabel13.setToolTipText("");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, 20));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 0, 51));
        jLabel19.setText("Estado:");
        jLabel19.setToolTipText("");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, 20));

        txtIdPerLPAEst.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtIdPerLPAEst.setForeground(new java.awt.Color(0, 102, 102));
        txtIdPerLPAEst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtIdPerLPAEst.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtIdPerLPAEst.setEnabled(false);
        jPanel2.add(txtIdPerLPAEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 40, 20));

        txtSerieGuia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtSerieGuia.setForeground(new java.awt.Color(0, 102, 102));
        txtSerieGuia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSerieGuia.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtSerieGuia.setEnabled(false);
        jPanel2.add(txtSerieGuia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 70, 20));

        jcbEstado.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jcbEstado.setForeground(new java.awt.Color(0, 0, 153));
        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jcbEstado.setToolTipText("");
        jcbEstado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jPanel2.add(jcbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 110, 20));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 0, 51));
        jLabel21.setText("IdLPAEst:");
        jLabel21.setToolTipText("");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        txtDniRuc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtDniRuc.setForeground(new java.awt.Color(0, 102, 102));
        txtDniRuc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDniRuc.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtDniRuc.setEnabled(false);
        jPanel2.add(txtDniRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 100, 20));

        txtCPDisp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCPDisp.setForeground(new java.awt.Color(0, 102, 102));
        txtCPDisp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCPDisp.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtCPDisp.setEnabled(false);
        jPanel2.add(txtCPDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 100, 20));

        txtCertificado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCertificado.setForeground(new java.awt.Color(0, 102, 102));
        txtCertificado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCertificado.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtCertificado.setEnabled(false);
        jPanel2.add(txtCertificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 110, 20));

        txtIdSuc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtIdSuc.setForeground(new java.awt.Color(0, 102, 102));
        txtIdSuc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtIdSuc.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtIdSuc.setEnabled(false);
        txtIdSuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdSucActionPerformed(evt);
            }
        });
        jPanel2.add(txtIdSuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 50, 20));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 51));
        jLabel3.setText("idSuc:");
        jLabel3.setToolTipText("");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 40, 20));

        txtIdCC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtIdCC.setForeground(new java.awt.Color(0, 102, 102));
        txtIdCC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtIdCC.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtIdCC.setEnabled(false);
        txtIdCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCCActionPerformed(evt);
            }
        });
        jPanel2.add(txtIdCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 50, 20));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 51));
        jLabel5.setText("idCC:");
        jLabel5.setToolTipText("");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, 20));

        txtCorrelativo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCorrelativo.setForeground(new java.awt.Color(0, 102, 102));
        txtCorrelativo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCorrelativo.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtCorrelativo.setEnabled(false);
        jPanel2.add(txtCorrelativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 100, 20));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 51));
        jLabel6.setText("Correlativo:");
        jLabel6.setToolTipText("");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, 20));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 0, 51));
        jLabel26.setText("Nombre Estimado:");
        jLabel26.setToolTipText("");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, 20));

        txtNomLPAEst.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNomLPAEst.setForeground(new java.awt.Color(0, 102, 102));
        txtNomLPAEst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtNomLPAEst.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtNomLPAEst.setEnabled(false);
        jPanel2.add(txtNomLPAEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 270, 20));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 0, 51));
        jLabel27.setText("idOrga:");
        jLabel27.setToolTipText("");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, 20));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 0, 51));
        jLabel28.setText("idPersona:");
        jLabel28.setToolTipText("");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        txtCodPro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCodPro.setForeground(new java.awt.Color(0, 102, 102));
        txtCodPro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCodPro.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtCodPro.setEnabled(false);
        jPanel2.add(txtCodPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 90, 20));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 0, 51));
        jLabel29.setText("Nombre Agricultor:");
        jLabel29.setToolTipText("");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, 20));

        txtNomPro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNomPro.setForeground(new java.awt.Color(0, 102, 102));
        txtNomPro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtNomPro.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtNomPro.setEnabled(false);
        jPanel2.add(txtNomPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 270, 20));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(153, 0, 51));
        jLabel30.setText("CPDISP:");
        jLabel30.setToolTipText("");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        txtIdPersona.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtIdPersona.setForeground(new java.awt.Color(0, 102, 102));
        txtIdPersona.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtIdPersona.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtIdPersona.setEnabled(false);
        jPanel2.add(txtIdPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 40, 20));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(153, 0, 51));
        jLabel31.setText("idCp:");
        jLabel31.setToolTipText("");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, 20));

        txtIdCpPro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtIdCpPro.setForeground(new java.awt.Color(0, 102, 102));
        txtIdCpPro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtIdCpPro.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtIdCpPro.setEnabled(false);
        jPanel2.add(txtIdCpPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 90, 20));

        txtIdOrgaPro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtIdOrgaPro.setForeground(new java.awt.Color(0, 102, 102));
        txtIdOrgaPro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtIdOrgaPro.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtIdOrgaPro.setEnabled(false);
        jPanel2.add(txtIdOrgaPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 90, 20));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(153, 0, 51));
        jLabel32.setText("Dni:");
        jLabel32.setToolTipText("");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(153, 0, 51));
        jLabel33.setText("CodAgricultor:");
        jLabel33.setToolTipText("");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(153, 0, 51));
        jLabel35.setText("ORGDISP:");
        jLabel35.setToolTipText("");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, 20));

        txtORGDisp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtORGDisp.setForeground(new java.awt.Color(0, 102, 102));
        txtORGDisp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtORGDisp.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtORGDisp.setEnabled(false);
        jPanel2.add(txtORGDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 100, 20));

        txtFTDisp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtFTDisp.setForeground(new java.awt.Color(0, 102, 102));
        txtFTDisp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtFTDisp.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtFTDisp.setEnabled(false);
        jPanel2.add(txtFTDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 100, 20));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(153, 0, 51));
        jLabel36.setText("FTDISP:");
        jLabel36.setToolTipText("");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, 20));

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(153, 0, 51));
        jLabel38.setText("RAINFDISP:");
        jLabel38.setToolTipText("");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 20));

        txtRainfDisp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtRainfDisp.setForeground(new java.awt.Color(0, 102, 102));
        txtRainfDisp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtRainfDisp.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtRainfDisp.setEnabled(false);
        jPanel2.add(txtRainfDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 100, 20));

        txtConvDisp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtConvDisp.setForeground(new java.awt.Color(0, 102, 102));
        txtConvDisp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtConvDisp.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtConvDisp.setEnabled(false);
        jPanel2.add(txtConvDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 90, 20));

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(153, 0, 51));
        jLabel39.setText("CONVDISP:");
        jLabel39.setToolTipText("");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, 20));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 51), 1, true), "Datos modificables de la conformación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 11), new java.awt.Color(153, 0, 51))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 51));
        jLabel8.setText("SACOS:");
        jLabel8.setToolTipText("");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 51));
        jLabel9.setText("KB:");
        jLabel9.setToolTipText("");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, 20));

        txtKb.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtKb.setForeground(new java.awt.Color(0, 0, 102));
        txtKb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(txtKb, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 80, -1));

        txtSacos.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtSacos.setForeground(new java.awt.Color(0, 0, 102));
        txtSacos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(txtSacos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 70, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 51));
        jLabel10.setText("TARA:");
        jLabel10.setToolTipText("");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, 20));

        txtTara.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtTara.setForeground(new java.awt.Color(0, 0, 102));
        txtTara.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtTara.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtTara.setEnabled(false);
        jPanel3.add(txtTara, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 90, -1));

        txtKN.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtKN.setForeground(new java.awt.Color(0, 0, 102));
        txtKN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(txtKN, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 90, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 51));
        jLabel11.setText("KN:");
        jLabel11.setToolTipText("");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, 20));

        txtLiqCompra.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtLiqCompra.setForeground(new java.awt.Color(0, 0, 102));
        txtLiqCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(txtLiqCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 90, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 0, 51));
        jLabel12.setText("LIQCOMPRA:");
        jLabel12.setToolTipText("");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, 20));

        txtGuia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtGuia.setForeground(new java.awt.Color(0, 102, 102));
        txtGuia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtGuia.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtGuia.setEnabled(false);
        jPanel3.add(txtGuia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 90, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 51));
        jLabel14.setText("GUIA:");
        jLabel14.setToolTipText("");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        txtImpTotal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtImpTotal.setForeground(new java.awt.Color(0, 102, 102));
        txtImpTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtImpTotal.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtImpTotal.setEnabled(false);
        jPanel3.add(txtImpTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 100, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 0, 51));
        jLabel15.setText("IMPORTE TOTAL:");
        jLabel15.setToolTipText("");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, 20));

        txtPrecio.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(0, 0, 102));
        txtPrecio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 70, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 0, 51));
        jLabel16.setText("PRECIO:");
        jLabel16.setToolTipText("");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 0, 51));
        jLabel17.setText("FECHA:");
        jLabel17.setToolTipText("");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, 20));
        jPanel3.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 110, -1));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 0, 51));
        jLabel22.setText("idLPACon:");
        jLabel22.setToolTipText("");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        txtIdProLPACon.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtIdProLPACon.setForeground(new java.awt.Color(0, 102, 102));
        txtIdProLPACon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtIdProLPACon.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtIdProLPACon.setEnabled(false);
        jPanel3.add(txtIdProLPACon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 40, -1));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 0, 51));
        jLabel20.setText("Nombre Contable:");
        jLabel20.setToolTipText("");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, 20));

        txtNomLPACon.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNomLPACon.setForeground(new java.awt.Color(0, 102, 102));
        txtNomLPACon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtNomLPACon.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtNomLPACon.setEnabled(false);
        jPanel3.add(txtNomLPACon, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 190, -1));

        btnBuscarPro.setBackground(new java.awt.Color(0, 102, 153));
        btnBuscarPro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuscarPro.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPro.setText("Buscar");
        jPanel3.add(btnBuscarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 90, -1));

        btnActualizar.setBackground(new java.awt.Color(0, 102, 153));
        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setEnabled(false);
        jPanel3.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 90, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 500, 160));

        btnCancelar.setBackground(new java.awt.Color(204, 0, 51));
        btnCancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon("D:\\Sistema\\Imagenes\\icons8_Save_20px.png")); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 100, 30));

        txtIdDetDoc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtIdDetDoc.setForeground(new java.awt.Color(0, 102, 102));
        txtIdDetDoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtIdDetDoc.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtIdDetDoc.setEnabled(false);
        txtIdDetDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdDetDocActionPerformed(evt);
            }
        });
        jPanel2.add(txtIdDetDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 60, 20));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 51));
        jLabel7.setText("idDetDoc");
        jLabel7.setToolTipText("");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 0, 51));
        jLabel18.setText("idDoct:");
        jLabel18.setToolTipText("");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, 20));

        txtIdDocT.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtIdDocT.setForeground(new java.awt.Color(0, 102, 102));
        txtIdDocT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtIdDocT.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtIdDocT.setEnabled(false);
        txtIdDocT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdDocTActionPerformed(evt);
            }
        });
        jPanel2.add(txtIdDocT, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 60, 20));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 0, 51));
        jLabel23.setText("Recuerda que luego de buscar debes actualizar.");
        jLabel23.setToolTipText("");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 530, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEmpActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtIdSucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdSucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdSucActionPerformed

    private void txtIdCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCCActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtIdDetDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdDetDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdDetDocActionPerformed

    private void txtIdDocTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdDocTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdDocTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnBuscarPro;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JComboBox<String> jcbEstado;
    public javax.swing.JTextField txtCPDisp;
    public javax.swing.JTextField txtCertificado;
    public javax.swing.JTextField txtCodPro;
    public javax.swing.JTextField txtConvDisp;
    public javax.swing.JTextField txtCorrelativo;
    public javax.swing.JTextField txtDniRuc;
    public javax.swing.JTextField txtFTDisp;
    public com.toedter.calendar.JDateChooser txtFecha;
    public javax.swing.JTextField txtGuia;
    public javax.swing.JTextField txtIdCC;
    public javax.swing.JTextField txtIdCpPro;
    public javax.swing.JTextField txtIdDetDoc;
    public javax.swing.JTextField txtIdDocT;
    public javax.swing.JTextField txtIdEmp;
    public javax.swing.JTextField txtIdOrgaPro;
    public javax.swing.JTextField txtIdPerLPAEst;
    public javax.swing.JTextField txtIdPersona;
    public javax.swing.JTextField txtIdProLPACon;
    public javax.swing.JTextField txtIdSuc;
    public javax.swing.JTextField txtImpTotal;
    public javax.swing.JTextField txtKN;
    public javax.swing.JTextField txtKb;
    public javax.swing.JTextField txtLiqCompra;
    public javax.swing.JTextField txtNomLPACon;
    public javax.swing.JTextField txtNomLPAEst;
    public javax.swing.JTextField txtNomPro;
    public javax.swing.JTextField txtORGDisp;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JTextField txtRainfDisp;
    public javax.swing.JTextField txtSacos;
    public javax.swing.JTextField txtSerieGuia;
    public javax.swing.JTextField txtTara;
    // End of variables declaration//GEN-END:variables
}
